### PR TITLE
Removed term "deprotection"

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Comment by ekr** [comment]
I don't see a reason for this change 8446 already uses deprotect.

**Comment by hannestschofenig** [comment]
The problem is that the TLS 1.3 spec does not define the term either.

**Comment by ekr** [comment]
Well, because I thought it was obvious. However, if you can't understand TLS 1.3, then you can't understand DTLS 1.3, so I think the ship has sailed.

**Comment by ekr** [comment]
@hannestschofenig I think this is within our discretion and I think we should close it. LMK if you feel strongly.

**Pull request closed without merging**
