### PR TITLE
Allow immediate processing of handshake data, where possible

### PR DESCRIPTION
**Pull request by hanno-arm**
Change as agreed in https://mailarchive.ietf.org/arch/msg/tls/PLK-EW_bWIXV74nm_8gSHwu5cqk/.

### CODE REVIEW

**Comment by hanno-arm** [comment]
@ekr @chris-wood Any comments/concerns?

**Review by chris-wood — APPROVED** [review]
"Where possible" is a bit unclear, but I don't have any better suggestions at the moment.

**Review by kaduk — COMMENTED** [review]
I would be interested to see an alternative proposal that moves to a "MUST NOT discard" framing.  This version of "MUST buffer ... but MAY as an alternative process" feels a bit like giving conflicting advice.

I note that the "next expected handshake message sequence number" is  important here -- fragments of subsequent messages can be discarded.

**Comment by hanno-arm** [comment]
@kaduk Good idea!

What about this, @kaduk @ekr @chris-wood:
> When a DTLS implementation receives a handshake message fragment corresponding to the next expected handshake message sequence number, it MUST NOT discard it. It is RECOMMENDED that the implementation buffers such fragments until it has the entire handshake message, but it MAY also process the fragment immediately.

**Comment by chris-wood** [comment]
@hanno-arm this seems better given that it avoids the "where possible" ambiguity. @ekr, what do you think?

**Comment by hanno-arm** [comment]
@ekr Appreciate it's not the most important issue, but can you take a look so we can get this in one form or another?

**Comment by hanno-arm** [comment]
@ekr What are your concerns with the present version?

**Comment by ekr** [comment]
Well, originally I just thought my text was clearer. But now that I know that the intent is to allow out-of-order processing I have a technical objection.

**Comment by chris-wood** [comment]
Closing as proposed in #261.

**Pull request closed without merging**
